# Generated by Django 3.2 on 2022-04-16 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0028_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=40)),
                ('client_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('client_email', models.EmailField(max_length=254)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concession', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False, editable=False)),
                ('backend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.backend')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.company')),
                ('frontend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.frontend')),
            ],
        ),
    ]
