# Generated by Django 3.2 on 2022-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='project_no',
            field=models.CharField(default='CP22-001', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
