# Generated by Django 3.2 on 2022-04-16 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0001_initial'),
        ('fees', '0013_auto_20210414_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProjectBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_of_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymenttype')),
                ('received_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_projects.clientproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
