# Generated by Django 3.2 on 2022-04-16 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201204_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Administration'), (2, 'Accounts'), (3, 'Projects')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
